# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-06 08:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='keywords',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skuid', models.CharField(max_length=15)),
                ('url', models.CharField(max_length=50)),
                ('keywords', models.CharField(max_length=100)),
            ],
        ),
    ]
