# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-06 08:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keywords',
            name='keywords',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='keywords',
            name='skuid',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='keywords',
            name='url',
            field=models.CharField(max_length=100),
        ),
    ]
