# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-07 08:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_auto_20160406_1657'),
    ]

    operations = [
        migrations.AddField(
            model_name='keywords',
            name='price',
            field=models.FloatField(default=100.0),
            preserve_default=False,
        ),
    ]
